"""
Constants used throughout the application
"""

# HTTP status codes
HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_SERVER_ERROR = 500

# Prometheus constants
PROMETHEUS_DEFAULT_PORT = 9090
PROMETHEUS_DEFAULT_SCRAPE_INTERVAL = 10  # seconds

# Grafana constants
GRAFANA_DEFAULT_PORT = 3000
GRAFANA_DEFAULT_DASHBOARD_WIDTH = 12
GRAFANA_DEFAULT_DASHBOARD_HEIGHT = 6

# Logging constants
LOG_LEVEL_DEBUG = 'DEBUG'
LOG_LEVEL_INFO = 'INFO'
LOG_LEVEL_WARNING = 'WARNING'
LOG_LEVEL_ERROR = 'ERROR'
LOG_LEVEL_CRITICAL = 'CRITICAL'

# Other constants
DEFAULT_TIMEOUT = 30  # seconds
MAX_RETRIES = 3
